# Generated by Django 3.2.15 on 2022-09-08 12:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True, null=True, validators=[users.models.check_birthday]),
        ),
    ]
